### ISSUE TITLE
Prediction breaks for datasets with more than 100 classes

### ISSUE THREAD

**Issue by MaxSchambach** [soda-inria/tabicl#8]
Trying to use `TabICLClassifier` with a task with more than 100 classes, prediction fails. Running on GPU, the error is quite cryptic first seeing a lot of

```bash
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [11,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [20,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [22,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [50,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [62,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [111,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [113,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [125,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
```
then a final exception is raised with
```bash
Traceback (most recent call last):
  File "<path>/scratch.py", line 34, in <module>
    _ = clf.predict(X)  # in-context learning happens here
        ^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/sklearn/classifier.py", line 604, in predict
    proba = self.predict_proba(X)
            ^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/sklearn/classifier.py", line 551, in predict_proba
    outputs.append(self._batch_forward(Xs, ys, shuffle_patterns))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/sklearn/classifier.py", line 480, in _batch_forward
    out = self.model_(
          ^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/tabicl.py", line 330, in forward
    out = self._inference_forward(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/tabicl.py", line 260, in _inference_forward
    out = self.icl_predictor(
          ^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/learning.py", line 464, in forward
    out = self._inference_forward(R, y_train, return_logits, softmax_temperature, mgr_config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/learning.py", line 410, in _inference_forward
    probs = self._predict_hierarchical(ri[train_size:])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/learning.py", line 339, in _predict_hierarchical
    return process_node(self.root, R_test)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/learning.py", line 325, in process_node
    group_probs = self._predict_standard(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/learning.py", line 258, in _predict_standard
    out = self.inference_mgr(
          ^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/inference.py", line 373, in __call__
    outputs = forward_fn(**inputs_on_exe)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/learning.py", line 216, in _icl_predictions
    R[:, :train_size] = R[:, :train_size] + self.y_encoder(y_train.float())
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/layers.py", line 86, in forward
    return F.linear(one_hot, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasLtMatmul with transpose_mat1 1 transpose_mat2 0 m 512 n 202 k 10 mat1_ld 10 mat2_ld 10 result_ld 512 abcType 2 computeType 68 scaleType 0
ERROR conda.cli.main_run:execute(125): `conda run python /home/azureuser/dev_sync/gpt4hana-baselines/scripts/scratch.py` failed. (See above for error)
```

on CPU the problem becomes more appearent:

```bash
  File "<path>/scratch.py", line 34, in <module>
    _ = clf.predict(X)
        ^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/sklearn/classifier.py", line 604, in predict
    proba = self.predict_proba(X)
            ^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/sklearn/classifier.py", line 551, in predict_proba
    outputs.append(self._batch_forward(Xs, ys, shuffle_patterns))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/sklearn/classifier.py", line 480, in _batch_forward
    out = self.model_(
          ^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/tabicl.py", line 330, in forward
    out = self._inference_forward(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/tabicl.py", line 260, in _inference_forward
    out = self.icl_predictor(
          ^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/learning.py", line 464, in forward
    out = self._inference_forward(R, y_train, return_logits, softmax_temperature, mgr_config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/learning.py", line 410, in _inference_forward
    probs = self._predict_hierarchical(ri[train_size:])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/learning.py", line 339, in _predict_hierarchical
    return process_node(self.root, R_test)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/learning.py", line 325, in process_node
    group_probs = self._predict_standard(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/learning.py", line 258, in _predict_standard
    out = self.inference_mgr(
          ^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/inference.py", line 375, in __call__
    outputs = forward_fn(**inputs_on_exe)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/learning.py", line 216, in _icl_predictions
    R[:, :train_size] = R[:, :train_size] + self.y_encoder(y_train.float())
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>/python3.11/site-packages/tabicl/model/layers.py", line 85, in forward
    one_hot = F.one_hot(src.long(), self.num_classes).to(src.dtype)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Class values must be smaller than num_classes.
```

I understand that TabICL is natively limited to 10 classes but I used the default active hierarchical prediction so I am not sure why it breaks for more than 100 target classes but does not seem like a coincidence when using a log10 for the hierarchical partitioning of the problem requiring more than 10 predictions 🙃

Code to reproduce:
```python


import numpy as np
from tabicl import TabICLClassifier

from tqdm import tqdm


def get_classifcation_data(num_classes: int, num_features: int, num_samples: int):
    assert num_samples > num_classes
    # Random feature matrix
    X = np.random.randn(num_samples, num_features)
    # Random target vector, making sure that every class appears at least once
    y = np.concatenate([np.arange(num_classes), np.random.randint(0, num_classes, size=num_samples-num_classes)])
    y = np.random.permutation(y)
    assert np.unique(y).size == num_classes
    return X, y


np.random.seed(42)
failures = []
for num_classes in tqdm([99, 100, 101, 102]):

    X, y = get_classifcation_data(
        num_classes=num_classes,
        num_features=10,
        num_samples=2*num_classes,
    )

    clf = TabICLClassifier()

    try:
        clf.fit(X, y)
        _ = clf.predict(X)
    except Exception as e:
        print(f"Failed for: {num_classes}")
        failures.append((num_classes, e))

print("RESULTS:")
for failure in failures:
    print("-", failure)
```

Run with `tabicl=0.1.1` and latest model checkpoint.

**Comment by JingangQu** [comment]
Hello,

Thanks for reporting this bug — we've successfully reproduced the issue.

The problem occurs in the `_grouping` method of `ICLearning`. When the number of classes (`num_classes`) exceeds the square of `max_classes`, the number of child groups calculated as `math.ceil(num_classes / self.max_classes)` will also exceed `max_classes`. This violates the internal node design, which allows at most `max_classes` distinct child groups.

We've fixed the bug by capping the number of groups at `max_classes` using the following logic:

```python
num_groups = min(math.ceil(num_classes / self.max_classes), self.max_classes)
```

Given max_classes=10 and num_classes=101, the fixed `_grouping` method:
  - Distributes 101 classes into 10 groups. Sizes: [11, 10, 10, 10, 10, 10, 10, 10, 10, 10].
  - Returns assignments tensor and num_groups = 10.
  - The child node receiving 11 classes will be further divided into 2 groups: [6, 5].


You can verify the fix with the following code:

```python
import numpy as np
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from tabicl import TabICLClassifier

X, y = make_blobs(n_samples=[20] * 101, n_features=2, cluster_std=0.1, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, stratify=y, random_state=42)

clf = TabICLClassifier()
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, predictions))
```

Let us know if you encounter any further issues.

**Comment by MaxSchambach** [comment]
Thank you for the super quick response and fix! Indeed I can confirm that it solves the above issue. 🙌

Tested with version 0.1.2.
